name: eventsbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  logger: ^2.3.0
  fluttertoast: ^8.2.5
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.3.3+1
  add_2_calendar: ^3.0.1
  url_launcher: ^6.2.6
  provider: ^6.1.2
  image_picker: ^1.1.2
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  dio: ^5.4.3+1
  image_cropper: ^4.0.0
  badges: ^3.1.2
  socket_io_client: ^1.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
